name: A4091 Logic CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: stefanreinauer/wincupl

    steps:
    - uses: actions/checkout@v4

    - name: Build JEDEC files
      run: make

    - name: List PLD files
      run: ls -alh source/u*.pld

    - name: Create zip
      run: |
        tar -cvzf A4091_Logic_Artifacts.tar.gz jedec/ source/

    - name: Upload tar.gz artifacts
      uses: actions/upload-artifact@v4
      with:
        name: A4091 Logic Artifacts
        path: A4091_Logic_Artifacts.tar.gz

