name: A4091 Logic CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: stefanreinauer/wincupl

    steps:
    - uses: actions/checkout@v4

    - name: Build JEDEC files
      run: make

    - name: Archive CI artifacts (JED and PLD)
      uses: actions/upload-artifact@v4
      with:
        name: A4091 Logic Artifacts
        path: |
          ${{ github.workspace }}/jedec/u*.jed
          ${{ github.workspace }}/source/u*.pld
