name: A4091 Logic Release

on:
  release:
    types: [created]  # Trigger only when a new release is created

jobs:
  build:

    runs-on: ubuntu-latest
    container: stefanreinauer/wincupl

    steps:
    - uses: actions/checkout@v4

    - name: Build JEDEC files
      run: make

    - name: Archive CI artifacts (JED and PLD)
      uses: actions/upload-artifact@v4
      with:
          name: A4091 Artifacts
          path: |
            ${{ github.workspace }}/jedec/u*.jed
            ${{ github.workspace }}/source/u*.pld

    - name: Upload JEDEC Files to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ github.workspace }}/jedec/u*.jed
        asset_name: A4091_JEDEC_files.zip  # You can zip the files if needed
        asset_content_type: application/zip

    - name: Upload PLD Files to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ github.workspace }}/source/u*.pld
        asset_name: A4091_PLD_files.zip  # You can zip the files if needed
        asset_content_type: application/zip
